// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs12sP_w7hiyVNwBiU2f6ucRraaT_1y_Q',
    appId: '1:84261668365:web:1eaa9a0da61225eeb37744',
    messagingSenderId: '84261668365',
    projectId: 'valaisroll',
    authDomain: 'valaisroll.firebaseapp.com',
    storageBucket: 'valaisroll.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_GFsVKbwlZkZEEFIchgDhcPGViuWHcA',
    appId: '1:84261668365:android:e2c4869c35a6fbfcb37744',
    messagingSenderId: '84261668365',
    projectId: 'valaisroll',
    storageBucket: 'valaisroll.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8u--5Ells-mRQEmm-J9rWroMLQSZbuEk',
    appId: '1:84261668365:ios:6cef752dde8487f2b37744',
    messagingSenderId: '84261668365',
    projectId: 'valaisroll',
    storageBucket: 'valaisroll.appspot.com',
    iosBundleId: 'com.example.valaisRoll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8u--5Ells-mRQEmm-J9rWroMLQSZbuEk',
    appId: '1:84261668365:ios:6cef752dde8487f2b37744',
    messagingSenderId: '84261668365',
    projectId: 'valaisroll',
    storageBucket: 'valaisroll.appspot.com',
    iosBundleId: 'com.example.valaisRoll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs12sP_w7hiyVNwBiU2f6ucRraaT_1y_Q',
    appId: '1:84261668365:web:280137227efdcf69b37744',
    messagingSenderId: '84261668365',
    projectId: 'valaisroll',
    authDomain: 'valaisroll.firebaseapp.com',
    storageBucket: 'valaisroll.appspot.com',
  );
}
